name: Build mingw

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      shell: 'C:\shells\msys2bash.cmd {0}'
      run: pacman -S --noconfirm --needed --noprogressbar ninja nasm mingw-w64-i686-gcc
    - name: Build
      shell: 'C:\shells\msys2bash.cmd {0}'
      run: |
        export PATH=$PATH:/mingw32/bin/
        ninja -v
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: CPU73050-${{ github.sha }}.dll
        path: ./obj/CPU73050.dll
    - name: Update release
      if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'created')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./obj/CPU73050.dll
        asset_name: CPU73050-${{ github.sha }}.dll
        asset_content_type: application/x-dosexec
